### ISSUE TITLE
[Tizen.Applications.WatchfaceComplication] ComplicationProvider period is still the same.

### ISSUE THREAD

**Issue by Machinero** [Samsung/TizenFX#1470]
No matter what i put in "Period" tag in tizen-manifest.xml file, the refresh rate of ComplicationProvider is still 60 seconds.

**Comment by gotoextreme** [comment]
@Machinero What values did you put in? If the value is less than 60, we intentionally do not allow an update period of less than 60 seconds since too frequent updates may impact battery life.
It seems period value restriction is not applied to the SDK tizen-manifest.xml editor. I will report it to the SDK team.

**Comment by Machinero** [comment]
@gotoextreme Thank you for reply. I have check this again i haven't notice that id of service hasn't changed and that why period didn't change. 

I apologize for the mix-up.
