### ISSUE TITLE
Tizen 5 Popup styles

### ISSUE THREAD

**Issue by sondavide** [Samsung/TizenFX#2177]
Hi, with Tizen 4.0.0.7, using Elmsharp library, I could create custom Popup with a desired background color, using I.E. these methods:

```
Popup _myPopup = new Popup(TForms.NativeParent);
_myPopup.Style = "circle";
Layout _myLayout = new Layout(_myPopup);

_myLayout.SetTheme("layout","popup","content/circle");
_myPopup.BackgroundColor = Color.Red.ToNative( );
...
_myPopup.SetContent(_myLayout);
_myPopup.Show();
```

With Tizen 5.5.0.1 using the same methods the popups has its default style, with background black and text white.
How can a cast the styles of the popups in Tizen 5?

**Comment by arosis78** [comment]
I checked and It's a bug.
This issue is fixed and it will be applied in the next MR version.

You can temporarily use below code for popup background color before it is applied.

Popup _myPopup = new Popup(TForms.NativeParent);
_myPopup.Style = "circle";

Layout bgLayout = new Layout(popup);
bgLayout.SetTheme("layout", "application", "default");
_myPopup.SetContent(_myLayout);

Rectangle bg = new Rectangle(bgLayout);
bg.Color = Color.Red.ToNative( );
bgLayout.SetPartContent("elm.swallow.bg", bg);

Layout _myLayout = new Layout(_myPopup);
_myLayout.SetTheme("layout","popup","content/circle");
bgLayout.SetContent(layout);
...

_myPopup.Show();
